name: Build and Deploy Pages

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: yarn install
      - name: Build pages
        env:
          NUXT_ENV_BASE_URL: https://autozp.me
          NUXT_ENV_API_URL: https://api.autozp.me
        run: |
          printf "BASE_URL=https://autozp.me\nAPI_URL=https://api.autozp.me" > .env
          node_modules/.bin/nuxt generate -sm --fail-on-error
      - name: Push pages
        run: |
          cd dist
          git init
          git config user.name "GitHub Actions"
          git remote add origin https://JingBh:${{ secrets.GITHUB_TOKEN }}@github.com/JingBh/autozp.git
          git add .
          git commit -m "Update pages"
          git push -f origin master:pages

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.DIRECTORY }}
            git fetch --all --force
            git reset --hard origin/pages
